export default {
  PLUSJAKARTASANS_BOLD: 'PlusJakartaSans-Bold',
  PLUSJAKARTASANS_BOLDITALIC: 'PlusJakartaSans-BoldItalic',
  PLUSJAKARTASANS_EXTRABOLD: 'PlusJakartaSans-ExtraBold',
  PLUSJAKARTASANS_EXTRABOLDITALIC: 'PlusJakartaSans-ExtraBoldItalic',
  PLUSJAKARTASANS_EXTRALIGHT: 'PlusJakartaSans-ExtraLight',
  PLUSJAKARTASANS_EXTRALIGHTITALIC: 'PlusJakartaSans-ExtraLightItalic',
  PLUSJAKARTASANS_ITALIC: 'PlusJakartaSans-Italic',
  PLUSJAKARTASANS_LIGHT: 'PlusJakartaSans-Light',
  PLUSJAKARTASANS_LIGHTITALIC: 'PlusJakartaSans-LightItalic',
  PLUSJAKARTASANS_MEDIUM: 'PlusJakartaSans-Medium',
  PLUSJAKARTASANS_REGULAR: 'PlusJakartaSans-Regular',
  PLUSJAKARTASANS_SEMIBOLD: 'PlusJakartaSans-SemiBold',
  INTER_REGULAR: 'Inter-Regular',
  INTER_SEMIBOLD: 'Inter-SemiBold',
  MULISH_BOLD: 'Mulish-Bold',
  MULISH_REGULAR: 'Mulish-Regular',
  MULISH_MEDIUM: 'Mulish-MEDIUM',
  MULISH_SEMIBOLD: 'Mulish-SemiBold',
  IBMPLEXMONO_BOLD: 'IBMPlexMono-Bold',
};
